### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by jonaskello** [dividab/uom#21]
So there has been some breaking changes merged into master lately. Most of them are just to undocumented API but still there are apps using these undocumented API so we need to increment the major version. The changes I know of are recorded in the change log. If anyone know of more changes that have been done please add them too.

So any more changes we want to do before releasing 2.0.0?

**Comment by jonaskello** [comment]
A plan to solve #19 might be nice before 2.0?

**Comment by Jontem** [comment]
2.0 is released
