### ISSUE TITLE
AlternateUnit, BaseUnit and ProductUnit don't use their type parameter.

### ISSUE THREAD

**Issue by geon** [dividab/uom#6]
Apparently this is a big no-no.

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--

**Comment by Jontem** [comment]
I believe this is fixed now.
